language: ruby
cache: bundler

rvm:
  - 2.4.5

before_install:
  - gem update --system
  - gem install bundler

env:
  - RACK_ENV=test
  
script:
 — bundle install --jobs=3 --retry=3
 — bundle exec rake db:create 
 — bundle exec rake db:migrate
 — bundle exec rspec
  
deploy:
  provider: heroku
  api_key:
    secure: S+jwv843LfAaBLPY7+t/K0ntlZSdwmvKN2YbLBuBolxk9WRdFXlxriVV3YvrFo3JduwgKI7bdMy4qwl/SUG9bw4Zp5GfBorqaBc0xFvAklGmxeYvAUr/3BRSRiobNXosYl9PzT4j/8rRzSNqac4myvX2PlPBw6E/M9TXD2IbH3TuqA9Gpic9PWCNJaw0fdrWAsjzJJFXngqJAxIktOtnqYCqqUgcn8ki2mXrUMxmzB28UAXfNDR2vDXqPFiHHvVpvfkH8/iHGd5F2737sOIg40WBVZvSLn5Lg3zHba2IO6yE4pG1fH8Q8xMkwYIKKl+7Xhs2aOu0AwDg9Ms2ZbeBPoiEJQrZAjpHqaHcCGDKl+1J+tO3+3hzBzR4+IVQqpQ6nOLbNdMAEYPp9kcKTut/lwLuW0d8BWN+uYBqVi5IIN/GjzYWc18jrMpvImrmKBwytv8ZvxlXJtuCwjKe1BxjEcE8Mirppx2+XH3qrWyAFtcZUyEagjjSETkmVx4XyORvzdbDRDDUyn7X3QsYTQPtAw60AifEqZYWJrnIFNOloCv8/6yPXGcwzEMOPMQmLwgh6LCdUbyt+qIVRR++Ou7QasKy4ZmaLSNgAtHQ/8C6SzfettS8m9TIOcCNl/0mZVw/Viir9TRlbWLEQEsDY6QOguZOsmvNtw1sDGnG9bOzEQ8=
